### ISSUE TITLE
Error for listen node

### ISSUE THREAD

**Issue by mshaz** [jeancarl/node-red-contrib-virtual-tjbot#2]
![image](https://user-images.githubusercontent.com/16055146/49631753-2c17d880-fa2e-11e8-8eb4-971f9b7847e8.png)

Hi I need help. Other nodes are working but the listen node is not. It gave such error in the picture when i click deploy button. 

I put the API correctly and the mic is working when tested using terminal command. 

Thank you.

**Comment by jeancarl** [comment]
This was caused by a bug in the config node that wasn't reading the API key field correctly. This has been fixed in 0.1.5. 

Update the package. You may also need to recreate (delete and create) the configuration of the virtual TJBot profile and re-enter the API keys.

Please confirm this resolves the issue.

**Comment by mshaz** [comment]
Hi thanks for replying, 

I use https://flows.nodered.org/node/node-red-contrib-virtual-tjbot and install frm the nodered palette. Am using free plan speech to text watson API. Do i have to pay? 

Error still not resolved. 

Thank you

**Comment by jeancarl** [comment]
Version 0.2.0 added additional error checking. Please let me know if this fixes the problem you've reported.

Per your question of using the service: a Lite Plan (no charge) instance of the Speech to Text service is capped at 100 free minutes of input audio. Your Lite Plan instance will be deleted after 30 days of inactivity.
